name: NPCRotation
version: "1.0"
api: ["1.0.0"]
author: PocketMiner82
description: "NPCs look at players, when they move! (ported SlapperRotation by jojoe77777 from PMMP to Nukkit)"
main: PocketMiner82.NPCRotation.NPCRotation
depend: [NPC]